-- db setup

-- DROP DATABASE doorway;

-- CREATE DATABASE doorway;

-- USE doorway;

-- user profile

CREATE TABLE user (
   id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(255) UNIQUE NOT NULL,
   name TEXT,
   nickname VARCHAR(255),
   password_digest TEXT NOT NULL,
   admin TINYINT(1),
   perms MEDIUMTEXT,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX email_ix ON user (email);

CREATE TABLE invite (
   id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(255) UNIQUE NOT NULL,
   jwtoken MEDIUMTEXT,
   perms MEDIUMTEXT,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX invite_email_ix ON invite (email);

CREATE TABLE forgotpassword (
   id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   user_id INT(10) UNIQUE NOT NULL,
   jwtoken MEDIUMTEXT,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
